# Utilisez une image Node.js en tant qu'image de base
FROM node:14

# Créez un répertoire de travail dans l'image
WORKDIR /app

# Copiez le fichier package.json et package-lock.json dans le répertoire de travail
COPY package*.json ./

# Installez les dépendances
RUN npm install

# Copiez le reste des fichiers de l'application dans le répertoire de travail
COPY index.js ./

# Exposez le port 3000 sur le conteneur
EXPOSE 3000

# Commande pour démarrer l'application
CMD ["node", "index.js"]
